### ISSUE TITLE
log有回复,但是顶顶不显示

### ISSUE THREAD

**Issue by Raytow** [mggger/chatgpt-bot-dingding#2]
2023-02-11 05:49:08,391 INFO     ChatgptHandler[75] dingding: {'errcode': 310000, 'errmsg': '错误描述:关键词不匹配;解决方案:请联系群管理员查看此机器人的关键词，并在发送的信息中包含此关键词;'}

**Comment by irx999** [comment]
error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False 这个怎么解决？

**Comment by irx999** [comment]
> 2023-02-11 05:49:08,391 INFO ChatgptHandler[75] dingding: {'errcode': 310000, 'errmsg': '错误描述:关键词不匹配;解决方案:请联系群管理员查看此机器人的关键词，并在发送的信息中包含此关键词;'}

钉钉机器人权限换成 ip  不要用关键词了

**Comment by mggger** [comment]
@irx999  这是open api的问题，已经加了重试逻辑了

**Comment by luzle** [comment]
试了下 没有反映了  之前还会打印日志 ChatgptHandler[75] dingding: {'errcode': 310000, 'errmsg': '错误描述:关键词不匹配;解决方案:请联系群管理员查看此机器人的关键词，并在发送的信息中包含此关键词;'}，后面在请求就没日志打印了

**Comment by luzle** [comment]
已收到，祝您生活快乐，身体健康
