### ISSUE TITLE
可不可以支持连续对话？

### ISSUE THREAD

**Issue by cccRaim** [mggger/chatgpt-bot-dingding#3]
参考[https://www.v2ex.com/amp/t/915266](https://www.v2ex.com/amp/t/915266)  
python是不是有全局内存可以存的？  
以群聊+发送人为key存历史记录，满4096个字符就提示清空

**Comment by mggger** [comment]
@cccRaim 挺好的建议，后续会加上

**Comment by cccRaim** [comment]
【我做了一个开源ChatGPT客户端！比ChatGPT Plus还快！-哔哩哔哩】 https://b23.tv/k5Cb5kU  

![image](https://user-images.githubusercontent.com/7681138/223019691-99cd5749-af51-4595-a71f-e2f573a4660f.jpeg)  
这种感觉提示也挺好的
